# This is a basic workflow to help you get started with Actions

name: build-and-publish

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      isProduction:
        description: 'production build'
        type: boolean
        required: true
        default: 'false'
   
env:
  isProduction: 'false'
  MAJOR_VERSION: 1
  MINOR_VERSION: 0
  PATCH_VERSION: 8


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: npm install
        run: npm install

      - name: npm build
        run: npm run build
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: npm-publish-artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: |
            ./dist    
            ./package.json 
            ./major.txt
            ./minor.txt
            ./patch.txt
            ./.npmrc
  preview:
    runs-on: ubuntu-latest
    environment: preview
    if: ${{ github.run_attempt != 1 }}
    needs: [ build ]
    steps:

      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.0
        with:
          name: npm-publish-artifact

      - name: set up variable -- NpmPackageVersion
        run: echo "NpmPackageVersion=${{env.MAJOR_VERSION}}.${{ env.MINOR_VERSION }}.${{ env.PATCH_VERSION }}--preview-${{ github.run_id }}" >> $GITHUB_ENV

      - name: npm version
        run: npm version ${{ env.NpmPackageVersion }} --no-git-tag-version
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_USERNAME: ${{ secrets.NPM_USERNAME }}
          NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
          NPM_REGISTRY: ${{ secrets.NPM_REGISTRY }}

      - name: Npm publish
        run: npm publish  --access public  --tag next
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_USERNAME: ${{ secrets.NPM_USERNAME }}
          NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
          NPM_REGISTRY: ${{ secrets.NPM_REGISTRY }}

  production:
    runs-on: ubuntu-latest
    if: ${{ github.run_attempt != 1 }}
    environment: production
    needs: [ build, preview ]
    steps:

      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.0
        with:
          name: npm-publish-artifact

      - name: set up variable -- NpmPackageVersion
        run: echo "NpmPackageVersion=${{env.MAJOR_VERSION}}.${{ env.MINOR_VERSION }}.${{ env.PATCH_VERSION }}" >> $GITHUB_ENV


      - name: npm version
        run: npm version ${{ env.NpmPackageVersion }} --no-git-tag-version
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_USERNAME: ${{ secrets.NPM_USERNAME }}
          NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
          NPM_REGISTRY: ${{ secrets.NPM_REGISTRY }}

      - name: Npm publish
        run: npm publish  --access public  --tag latest
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_USERNAME: ${{ secrets.NPM_USERNAME }}
          NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
          NPM_REGISTRY: ${{ secrets.NPM_REGISTRY }}       
            
