name: build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      isProduction:
        description: 'production build'
        type: boolean
        required: true
        default: 'false'
   
env:
  isProduction: 'false'
  MAJOR_VERSION: 1
  MINOR_VERSION: 0
  PATCH_VERSION: 8


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  call-workflow:
    uses: Ke-Jin-Laserfiche/hello-github/.github/workflows/called.yml@validation
    with:
      version: ${{env.MAJOR_VERSION}}.${{env.MINOR_VERSION}}.${{env.PATCH_VERSION}}
