name: 'From N jobs to 1 job'

on:
  workflow_dispatch:

jobs:
  job-a:
  
    name: Job A
    runs-on: ubuntu-latest
    if: ${{ github.run_attempt != 1 }}
    steps:
      - run: echo "job A"

  job-b:
    name: Job B
    if: ${{ github.run_attempt != 1 }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "job B"

  job-c:
    name: Job C
    if: ${{ contains(needs.job-a.result, 'success') && contains(needs.job-b.result, 'success') }}
    runs-on: ubuntu-latest
    needs: [ job-a, job-b ]
    steps:
      - run: echo ${{needs.job-b}}
