# This is a basic workflow to help you get started with Actions

name: publish

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

    inputs:
      isProduction:
        description: 'production build'
        type: boolean
        required: true
        default: 'false'

env:
  MAJOR_VERSION: 1
  MINOR_VERSION: 0
  PATCH_VERSION: 2


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2


      - name: 'Echo build number'
        run: echo "${{github.run_id}}"
        
      - name: Echo workflow input isProduction
        run: echo ${{ github.event.inputs.isProduction }}
        
      - name: 'set up variable: NpmPackageVersion'
        if: ${{ github.event.inputs.isProduction == "true"}}
        run: echo "NpmPackageVersion=${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}.${{ env.PATCH_VERSION }}" >> $GITHUB_ENV
        
      - name: 'set up variable: NpmPackageVersion'
        if: ${{ ! github.event.inputs.isProduction  == "false"}}
        run: echo "NpmPackageVersion=${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}.${{ env.PATCH_VERSION }}--preview-${{ github.run_id }}" >> $GITHUB_ENV


      - name: npm version
        run: npm --prefix ./npm-publish version ${NpmPackageVersion}
        if: ${{ ! github.event.inputs.isProduction }}
          
      - name: npm version
        run: npm --prefix ./npm-publish version ${NpmPackageVersion}
        if: ${{ github.event.inputs.isProduction }}
          
      - name: npm publish
        run: npm publish ./npm-publish  --access public --tag next
        if: ${{ github.event.inputs.isProduction == "false" }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_USERNAME: ${{ secrets.NPM_USERNAME }}
          NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
          NPM_REGISTRY: ${{ secrets.NPM_REGISTRY }}


  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: production
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: npm publish
        run: npm publish ./npm-publish  --access public --tag latest
        if: ${{ github.event.inputs.isProduction == "true"}}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_USERNAME: ${{ secrets.NPM_USERNAME }}
          NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
          NPM_REGISTRY: ${{ secrets.NPM_REGISTRY }}