# This is a basic workflow to help you get started with Actions

name: publish

# Controls when the workflow will run
on:
  workflow_run:
    workflows: ["build"]
    types: [completed]

        
        

jobs:
  validation:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: ${{ github.run_attempt != 1 }} # automatically triggered has run_attempt == 1
    outputs:
      major: ${{ env.major }}
      minor: ${{ env.minor }}
      patch: ${{ env.patch }}

    steps:
      - uses: actions/checkout@v2
      - run: echo 'The triggering workflow passed'

      - name: echo git run_attempt
        run: echo ${{github.run_attempt }} 
      
      
      - name: echo github event
        run: echo "GitEventPayload=${{ github.run_attempt }}" >> $GITHUB_ENV

      - name: echo github event
        run: echo ${{env.GitEventPayload}}

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success

      - shell: bash
        run: |
          echo "major=`cat npm-publish-artifact/major.txt`" >> $GITHUB_ENV
          echo "minor=`cat npm-publish-artifact/minor.txt`" >> $GITHUB_ENV
          echo "patch=`cat npm-publish-artifact/patch.txt`" >> $GITHUB_ENV

      - name: echo major
        run: echo ${{env.major}}

      - name: echo minor
        run: echo ${{env.minor}}
        
      - name: echo patch
        run: echo ${{env.patch}}

  preview:
    runs-on: ubuntu-latest
    environment: production
    needs: [ validation ]
    steps:

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success

      - name: set up variable -- NpmPackageVersion
        run: echo "NpmPackageVersion=${{ needs.validation.outputs.major }}.${{ needs.validation.outputs.minor }}.${{ needs.validation.outputs.patch }}--preview-${{ github.run_id }}" >> $GITHUB_ENV

      - name: npm version
        run: npm version ${{ env.NpmPackageVersion }} --no-git-tag-version
        working-directory: ./npm-publish-artifact
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_USERNAME: ${{ secrets.NPM_USERNAME }}
          NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
          NPM_REGISTRY: ${{ secrets.NPM_REGISTRY }}

      - name: Npm publish
        run: npm publish  --access public  --tag next
        working-directory: ./npm-publish-artifact
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_USERNAME: ${{ secrets.NPM_USERNAME }}
          NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
          NPM_REGISTRY: ${{ secrets.NPM_REGISTRY }}

  production:
    runs-on: ubuntu-latest
    environment: production
    needs: [ validation, preview ]
    steps:

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success

      - name: set up variable -- NpmPackageVersion
        run: echo "NpmPackageVersion=${{ needs.validation.outputs.major }}.${{ needs.validation.outputs.minor }}.${{ needs.validation.outputs.patch }}" >> $GITHUB_ENV


      - name: npm version
        run: npm version ${{ env.NpmPackageVersion }} --no-git-tag-version
        working-directory: ./npm-publish-artifact
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_USERNAME: ${{ secrets.NPM_USERNAME }}
          NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
          NPM_REGISTRY: ${{ secrets.NPM_REGISTRY }}

      - name: Npm publish
        run: npm publish  --access public  --tag latest
        working-directory: ./npm-publish-artifact
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_USERNAME: ${{ secrets.NPM_USERNAME }}
          NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
          NPM_REGISTRY: ${{ secrets.NPM_REGISTRY }}

