# This is a basic workflow to help you get started with Actions

name: publish

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  workflow_run:
    workflows: ["build"]
    types: [completed]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'

      - name: echo github context
        run: echo ${{toJson(github)}}

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success

# This is a basic workflow to help you get started with Actions
