# This is a basic workflow to help you get started with Actions

name: publish

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  workflow_run:
    workflows: ["build"]
    types: [completed]

jobs:
  validation:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - run: echo 'The triggering workflow passed'

      - name: echo github context
        run: echo "GitEventPayload=${{ github.event.workflow_run.id }}" >> $GITHUB_ENV

      - name: echo github run id
        run: echo ${{env.GitEventPayload}}

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success

  preview:
    runs-on: ubuntu-latest
    environment: production
    needs: [ validation ]
    steps:

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success

      - shell: bash
        run: |
          echo "major=`cat major.txt`" >> $GITHUB_ENV
          echo "minor=`cat minor.txt`" >> $GITHUB_ENV
          echo "patch=`cat patch.txt`" >> $GITHUB_ENV

      - name: echo major
        run: echo ${{env.major}}

      - name: echo minor
        run: echo ${{env.minor}}
        
      - name: echo patch
        run: echo ${{env.patch}}

