name: test

on:
  push:

  pull_request:


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  publish_documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}

      - name: echo github head ref
        run: echo ${{ github.head_ref}}
      - name: Set GIT_BRANCH
        run: |
          # Short name for current branch. For PRs, use target branch (base ref)
          GIT_BRANCH=${github.head_ref:-${GITHUB_REF#refs/heads/}}
          echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV
          echo ${{env.GIT_BRANCH}}

